package config

// Modules
const PLACEHOLDER_PACKAGENAME = "%PACKAGE_NAME%"

// General
const PLACEHOLDER_APP_NAME = "%APP_NAME%"
const PLACEHOLDER_APP_PORT = "%APP_PORT%"

// JWT
const PLACEHOLDER_JWT_TOKEN = "%JWT_TOKEN%"

// gRPC
const PLACEHOLDER_GRPC_PORT = "%GRPC_PORT%"
const PLACEHOLDER_GRPC_EXT_HOST = "%GRPC_EXT_HOST%"
const PLACEHOLDER_GRPC_EXT_PORT = "%GRPC_EXT_PORT%"
const PLACEHOLDER_GRPC_EXT_SERVERNAME = "%GRP_SERVER_NAME%"
const PLACEHOLDER_GRPC_EXT_SERVICENAME = "%GRP_SERVICE_NAME%"

// MySQL
const PLACEHOLDER_MYSQL_DB = "%MYSQL_DBNAME%"
const PLACEHOLDER_MYSQL_HOST = "%MYSQL_HOST%"
const PLACEHOLDER_MYSQL_PORT = "%MYSQL_PORT%"
const PLACEHOLDER_MYSQL_USER = "%MYSQL_USER%"
const PLACEHOLDER_MYSQL_PASS = "%MYSQL_PASS%"

// RabbitMQ
const PLACEHOLDER_RMQ_HOST = "%RMQ_HOST%"
const PLACEHOLDER_RMQ_PORT = "%RMQ_PORT%"
const PLACEHOLDER_RMQ_USER = "%RMQ_USER%"
const PLACEHOLDER_RMQ_PASS = "%RMQ_PASS%"
const PLACEHOLDER_RMQ_EXCHANGE = "%RMQ_EXCHANGE%"
const PLACEHOLDER_RMQ_EXT_EXCHANGE = "%RMQ_EXT_EXCHANGE%"
const PLACEHOLDER_RMQ_EXT_SERVERNAME = "%RMQ_SERVER_NAME%"
